const Annonces = [
  {
    id: 1,
    image: "/images/apartment1.jpg",
    name: "Skyline Serenity Apartment",
    prix: "180,000",
    category: "Apartment",
    description: "Comfortable apartment perfect for city living.",
  },
  {
    id: 2,
    image: "/images/villa1.jpg",
    name: "Sunset Luxe Villa",
    prix: "450,000",
    category: "Villa",
    description: "Spacious villa with a garden and pool.",
  },
  {
    id: 3,
    image: "/images/apartment2.jpg",
    name: "Urban Nest Apartment",
    prix: "200,000",
    category: "Apartment",
    description: "Comfortable apartment perfect for city living.",
  },
  {
    id: 4,
    image: "/images/villa2.jpg",
    name: "Royal Palm Villa",
    prix: "380,000",
    category: "Villa",
    description: "Spacious villa with a garden and pool.",
  },
  {
    id: 5,
    image: "/images/apartment3.jpg",
    name: "Golden Horizon Apartment",
    prix: "290,000",
    category: "Apartment",
    description: "Comfortable apartment perfect for city living.",
  },
  {
    id: 6,
    image: "/images/villa3.jpg",
    name: "The Grand Mirage Villa",
    prix: "420,000",
    category: "Villa",
    description: "Spacious villa with a garden and pool.",
  },
  {
    id: 7,
    image: "/images/Hunt1.jpg",
    name: "Whispering Pines Hunt Lodge",
    prix: "310,000",
    category: "Hunt",
    description: "A peaceful getaway in nature.",
  },
  {
    id: 8,
    image: "/images/house1.jpg",
    name: "Maple Grove Family Home",
    prix: "250,000",
    category: "House",
    description: "Perfect home for the whole family.",
  },
  {
    id: 9,
    image: "/images/Hunt2.jpg",
    name: "Evergreen Escape Hunt Cabin",
    prix: "330,000",
    category: "Hunt",
    description: "A peaceful getaway in nature.",
  },
  {
    id: 10,
    image: "/images/house2.jpg",
    name: "The Willowbrook House",
    prix: "370,000",
    category: "House",
    description: "Perfect home for the whole family.",
  },
  {
    id: 11,
    image: "/images/Hunt3.jpg",
    name: "Cedar Creek Retreat",
    prix: "275,000",
    category: "Hunt",
    description: "A peaceful getaway in nature.",
  },
  {
    id: 12,
    image: "/images/house3.jpg",
    name: "Lavender Lane Home",
    prix: "300,000",
    category: "House",
    description: "Perfect home for the whole family.",
  },
];

export default Annonces;
